In [4]:
#read n integers from user and find the sum of the middle digits in it 
n=int(input("Enter n value"))
l=list(map(str,input("Enter values").split()))[:n]
s=0
for i in l:
    x=int(i[1])
    s+=x
print(s)

Enter n value4
Enter values122 455 788 366
21


- Types of data in real time
  1. Quantitavive and 
     - Represents the size/volume of data 
     - Discrete and continuous 
        - This type of data is fixed/constant
          - Ex: numbers on die: varies from 1 to 0
            - distance,color,nationality,size,etc
        - continous data means the value/data is continous 
  2. Qualitative
     - Data is observed and placed in terms of category
       - Ex: Data submission in feedback form
- Data and statistics
  - nominal,ordinal,interval and radio
        

#### importing module
- Numpy
- Pandas
- Matplotlib and seaborn

In [8]:
import numpy 


In [9]:
# version of numpy
numpy.__version__

'1.20.1'

#### Numpy 
- Numpy stnds for numerical python
- which is used to deal with array type of data,scientific computation

##### array creation()
- array() is the submodule in numpy module
- np.array(iterable)

In [11]:
print(numpy.array([3,4,5,6,7,9,10]))#homogeneous data structure

[ 3  4  5  6  7  9 10]


In [12]:
t=numpy.array((5,6,7,8,9))

In [13]:
print(t)

[5 6 7 8 9]


In [15]:
ar=numpy.array([45.5,44.76,67.6,55.88])
ar

array([45.5 , 44.76, 67.6 , 55.88])

In [17]:
f1=numpy.array([34.56,459.65,558.36],dtype="float")
f1

array([ 34.56, 459.65, 558.36])

In [23]:
st=numpy.array([34.56,459.65,558.36],dtype='str')
st


array(['34.56', '459.65', '558.36'], dtype='<U6')

In [24]:
# Creating 1-D arrays
rn=numpy.array(range(10))
rn

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
r2=numpy.array(range(1,8))
r2

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
r3=numpy.array(range(1,8,2))
r3

array([1, 3, 5, 7])

In [27]:
r3.ndim

1

In [28]:
l2=numpy.array([[1,2,3,4],[5,6,7,8]])
l2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
l3=numpy.array([[[1,2,3,4],[5,6,7,8],[4,5,8,2]]])
l3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [4, 5, 8, 2]]])

In [30]:
l2.ndim

2

In [31]:
l3.ndim

3

In [32]:
l3.size

12

In [33]:
l3.shape

(1, 3, 4)

In [34]:
l3.itemsize


4

In [35]:
st.itemsize

24

In [22]:
# Unit matrixc
i=numpy.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
i2=numpy.eye(4,5)
i2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [37]:
l5=numpy.array([12,34,56],ndmin=10)
l5

array([[[[[[[[[[12, 34, 56]]]]]]]]]])

In [38]:
z=numpy.zeros(4)
z

array([0., 0., 0., 0.])

In [39]:
z=numpy.zeros((4,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
o=numpy.ones(5)
o

array([1., 1., 1., 1., 1.])

In [43]:
o2=numpy.ones((5,3))
o2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
f=numpy.full(4,'hi') # row size,ele
f

array(['hi', 'hi', 'hi', 'hi'], dtype='<U2')

In [49]:
f.fill('N')

f

array(['N', 'N', 'N', 'N'], dtype='<U2')

In [50]:
ln=numpy.linspace(10,200,10)
ln

array([ 10.        ,  31.11111111,  52.22222222,  73.33333333,
        94.44444444, 115.55555556, 136.66666667, 157.77777778,
       178.88888889, 200.        ])

In [52]:
print(numpy.arange(25))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


### Random()
- It is used to generate random variables within a range


In [2]:
import numpy as n
rns=n.random.randint(10)
rns

3

In [10]:
lw,up=map(int,input().split())
ri=n.random.randint(lw,up,8)
ri.reshape(2,4)

7 70


array([[64, 39, 16, 54],
       [ 8, 12, 23, 53]])

In [11]:
n.random.random((2,3))

array([[0.22836342, 0.47464004, 0.08965159],
       [0.8737767 , 0.76152173, 0.07532872]])

In [12]:
n.random.rand(4,3)

array([[0.38893253, 0.28165734, 0.64038693],
       [0.86107913, 0.98040578, 0.95922006],
       [0.64098515, 0.0423939 , 0.28601919],
       [0.44725653, 0.88340832, 0.65555867]])

In [14]:
n.random.randn(3,4)

array([[ 0.9969109 ,  0.6524848 , -0.29425183,  1.23786192],
       [-1.25116032,  0.31717464,  0.40811528,  0.66798768],
       [ 0.30767189,  0.48047435, -0.49574673,  0.73028752]])

In [15]:
n.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [16]:
n.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [19]:
help(n.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

### <u>Accessing the array elements</u>
-   ***using index we recognize array elwments***
-   ***Indexing is of 3 types***
-   ***+ve indexing,-ve indexing and fancy indexing***
1. **+ve indexing**
   - ***Traverse from left to right***
2. **-ve indexing**
   - ***Traverse from  right to left***
3. **Fancy indexing**
   - ***Condition Based index***

In [24]:
r=n.random.randint(50,200,25).reshape(5,-1)
r

array([[ 71,  77, 179, 179, 122],
       [143, 158, 121, 143, 145],
       [185,  54, 104, 117, 156],
       [131, 180, 196,  67, 108],
       [155,  77,  69, 111,  88]])

In [22]:
rr=n.random.randint(50,200,25).reshape(-1,5)
rr

array([[198,  81,  80,  64, 104],
       [118, 101, 174,  51, 174],
       [ 75,  73, 121, 129,  78],
       [ 97, 192, 186, 199, 124],
       [130,  76,  64, 131, 120]])

In [25]:
rr[3]

array([ 97, 192, 186, 199, 124])

In [26]:
r[:,1:4]

array([[ 77, 179, 179],
       [158, 121, 143],
       [ 54, 104, 117],
       [180, 196,  67],
       [ 77,  69, 111]])

In [27]:
sub=r[:,1:4]
for line in sub:
    for val in line:
        if val%2==1:
            print(val)

77
179
179
121
143
117
67
77
69
111


In [28]:
r.transpose()

array([[ 71, 143, 185, 131, 155],
       [ 77, 158,  54, 180,  77],
       [179, 121, 104, 196,  69],
       [179, 143, 117,  67, 111],
       [122, 145, 156, 108,  88]])

In [29]:
r<100


array([[ True,  True, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False,  True, False],
       [False,  True,  True, False,  True]])

In [30]:
r[r<100]

array([71, 77, 54, 67, 77, 69, 88])

In [31]:
s=n.random.randint(1,7)
print(s+r)

[[ 75  81 183 183 126]
 [147 162 125 147 149]
 [189  58 108 121 160]
 [135 184 200  71 112]
 [159  81  73 115  92]]


In [32]:
r+rr

array([[269, 158, 259, 243, 226],
       [261, 259, 295, 194, 319],
       [260, 127, 225, 246, 234],
       [228, 372, 382, 266, 232],
       [285, 153, 133, 242, 208]])

In [33]:
r*rr

array([[14058,  6237, 14320, 11456, 12688],
       [16874, 15958, 21054,  7293, 25230],
       [13875,  3942, 12584, 15093, 12168],
       [12707, 34560, 36456, 13333, 13392],
       [20150,  5852,  4416, 14541, 10560]])

In [34]:
r.mean()

125.44

In [35]:
r.sum()

3136

In [36]:
print(r.max())
r.min()

196


54

In [37]:
r

array([[ 71,  77, 179, 179, 122],
       [143, 158, 121, 143, 145],
       [185,  54, 104, 117, 156],
       [131, 180, 196,  67, 108],
       [155,  77,  69, 111,  88]])

In [38]:
r[0]

array([ 71,  77, 179, 179, 122])

In [3]:
import numpy as n
n.log(0)

<ipython-input-3-a8c9fb9096ee>:2: RuntimeWarning: divide by zero encountered in log
  n.log(0)


-inf

In [4]:
n.log(1)

0.0

In [5]:
n.log(10)

2.302585092994046

In [6]:
n.exp(1)

2.718281828459045

In [7]:
n.log(n.exp(7))

7.0

In [10]:
def greater(x,y):
    l=[]
    for i in range(len(x)):
        if(x[i]>y[i]):
            l.append(x[i])
        else:
            l.append(y[i])
    return l

In [12]:
print(greater([4,5,6],[7,3,9]))

[7, 5, 9]
